---
sudo: required
language: python
python: "2.7"

dist: trusty

#addons:
#  apt:
#    sources:
#      - deadsnakes
#    packages:
#      - python2.4
#      - python2.6
#      - python3.5

before_install:
  - env
  - echo '[all]' > hosts
  - |
    for i in 7 6 5; do
      # runlevel(8) hack. centos5's runlevel(8) needs to execute /sbin/init
      docker run --name centos$i -di centos:$i /sbin/init
      if [ $i = 5 ]; then
        docker exec centos$i yum install -y python-simplejson
      fi
      echo centos$i >> hosts
    done

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../:tests/roles' | tee ansible.cfg
  - cat hosts
  - pip install ansible-lint
  - ansible-lint --version

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i hosts tests/test.yml

notifications:
  email: false
