---

- name: Install gf repo.
  yum:
    name: "{{ repo_gf_release_url }}"
    state: present

- name: Enable/Disable repos.
  ini_file:
    dest: /etc/yum.repos.d/gf.repo
    section: "{{ item }}"
    option: enabled
    value: '{{ 1 if item in repo_gf_enable_repos else 0 }}'
    no_extra_spaces: yes
  with_items: "{{ repo_gf_repositories }}"
